apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location /app/ {
            proxy_pass http://spring-service:8080/;
        }

        location /admin/ {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /reports/ {
            root /usr/share/nginx/html;
            autoindex on;
        }
    }
